const express=require('express');const {pool}=require('../config/db');const {ok,fail}=require('../utils');const {requireAuth,allowRoles}=require('../middleware/auth');const router=express.Router();
router.get('/fleet-utilization',requireAuth,allowRoles('dispatcher','fleet_admin','auditor'),async(req,res)=>{try{const r=await pool.query(`SELECT vehicle_id,COUNT(*)::int trips,SUM(GREATEST(0,EXTRACT(EPOCH FROM (trip_end_timestamp-trip_start_timestamp))/3600))::numeric hours FROM reservations WHERE status IN('approved','active','completed') GROUP BY vehicle_id ORDER BY vehicle_id`);return ok(res,r.rows);}catch(e){return fail(res,500,'ANALYTICS_ERROR','Unable to calculate utilization.');}});
router.get('/booking-demand',requireAuth,async(req,res)=>{const r=await pool.query(`SELECT DATE(trip_start_timestamp) date,COUNT(*)::int bookings FROM reservations GROUP BY DATE(trip_start_timestamp) ORDER BY date`);return ok(res,r.rows);});
router.get('/fuel',requireAuth,async(req,res)=>{const r=await pool.query(`SELECT vehicle_id,COUNT(*)::int estimates,ROUND(AVG(estimated_liters),2) avg_estimated_liters FROM fuel_estimates GROUP BY vehicle_id ORDER BY vehicle_id`);return ok(res,r.rows);});
router.get('/fuel-variance',requireAuth,async(req,res)=>{const r=await pool.query(`SELECT reservation_id,estimated_fuel_liters,actual_fuel_liters,(actual_fuel_liters-estimated_fuel_liters) variance_liters FROM reservations WHERE actual_fuel_liters IS NOT NULL AND estimated_fuel_liters IS NOT NULL ORDER BY trip_end_timestamp DESC`);return ok(res,r.rows);});
router.get('/cost',requireAuth,async(req,res)=>{const r=await pool.query(`SELECT DATE(recorded_at) date,SUM(cost) total_cost FROM fuel_transactions GROUP BY DATE(recorded_at) ORDER BY date`);return ok(res,r.rows);});
router.get('/maintenance',requireAuth,async(req,res)=>{const r=await pool.query(`SELECT vehicle_id,status,COUNT(*)::int count FROM maintenance_records GROUP BY vehicle_id,status ORDER BY vehicle_id`);return ok(res,r.rows);});
router.get('/overview',requireAuth,async(req,res)=>{const v=await pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE service_status='available')::int available,COUNT(*) FILTER(WHERE service_status='maintenance')::int maintenance FROM vehicles`);const b=await pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='pending')::int pending,COUNT(*) FILTER(WHERE status='completed')::int completed FROM reservations`);const f=await pool.query(`SELECT COALESCE(SUM(actual_fuel_liters),0)::numeric actual_fuel,COALESCE(SUM(estimated_fuel_liters),0)::numeric estimated_fuel FROM reservations`);return ok(res,{vehicles:v.rows[0],reservations:b.rows[0],fuel:f.rows[0],filters:{from:req.query.from||null,to:req.query.to||null,vehicleType:req.query.vehicleType||null,vehicleId:req.query.vehicleId||null}});});
module.exports=router;
