const express = require('express');
const { pool } = require('../config/db');
const { ok, fail, userId } = require('../utils');
const { requireAuth, allowRoles } = require('../middleware/auth');
const router = express.Router();

async function operationalKpis(where = '', values = []) {
  const suffix = where ? `WHERE ${where}` : '';
  const result = await pool.query(`SELECT COUNT(*) FILTER (WHERE r.status='completed')::int trip_count,COALESCE(SUM(CASE WHEN r.status='completed' THEN COALESCE(t.actual_distance_km,r.route_km,0) ELSE 0 END),0)::numeric total_distance_km,COALESCE(SUM(CASE WHEN r.status='completed' THEN COALESCE(t.actual_fuel_used_liters,r.actual_fuel_liters,0) ELSE 0 END),0)::numeric actual_fuel_liters,COALESCE(SUM(CASE WHEN r.status='completed' THEN COALESCE(r.estimated_fuel_liters,0) ELSE 0 END),0)::numeric estimated_fuel_liters,COALESCE(SUM(ft.cost),0)::numeric fuel_cost FROM reservations r LEFT JOIN trips t ON t.reservation_id=r.reservation_id LEFT JOIN fuel_transactions ft ON ft.trip_id=t.trip_id ${suffix}`, values);
  const row = result.rows[0];
  return { tripCount: row.trip_count, totalDistanceKm: Number(row.total_distance_km), actualFuelLiters: Number(row.actual_fuel_liters), estimatedFuelLiters: Number(row.estimated_fuel_liters), fuelVarianceLiters: Number(row.actual_fuel_liters)-Number(row.estimated_fuel_liters), fuelCost: Number(row.fuel_cost) };
}
router.get('/requester',requireAuth,async(req,res)=>{try{const id=userId(req);const r=await pool.query(`SELECT status,COUNT(*)::int count FROM reservations WHERE requester_id=$1 GROUP BY status`,[id]);return ok(res,{reservations:r.rows,kpis:await operationalKpis('r.requester_id=$1',[id])});}catch{return fail(res,500,'DASHBOARD_ERROR','Unable to load requester dashboard.');}});
router.get('/dispatcher',requireAuth,allowRoles('dispatcher','fleet_admin'),async(_req,res)=>{try{const [p,a]=await Promise.all([pool.query(`SELECT COUNT(*)::int count FROM reservations WHERE status='pending'`),pool.query(`SELECT COUNT(*)::int count FROM reservations WHERE status='approved'`)]);return ok(res,{pendingReservations:p.rows[0].count,approvedReservations:a.rows[0].count,kpis:await operationalKpis()});}catch{return fail(res,500,'DASHBOARD_ERROR','Unable to load dispatcher dashboard.');}});
router.get('/driver',requireAuth,allowRoles('driver'),async(req,res)=>{try{const id=String(userId(req));const r=await pool.query(`SELECT COUNT(*)::int count FROM reservations WHERE driver_id IN(SELECT driver_id FROM drivers WHERE user_id=$1) AND status IN('approved','dispatched','active')`,[id]);return ok(res,{activeAssignments:r.rows[0].count,kpis:await operationalKpis(`r.driver_id IN(SELECT driver_id FROM drivers WHERE user_id=$1)`,[id])});}catch{return fail(res,500,'DASHBOARD_ERROR','Unable to load driver dashboard.');}});
router.get('/admin',requireAuth,allowRoles('fleet_admin'),async(_req,res)=>{try{const [v,r,t]=await Promise.all([pool.query(`SELECT COUNT(*)::int count FROM vehicles`),pool.query(`SELECT COUNT(*)::int count FROM reservations`),pool.query(`SELECT COUNT(*)::int count FROM trips`)]);return ok(res,{vehicles:v.rows[0].count,reservations:r.rows[0].count,trips:t.rows[0].count,kpis:await operationalKpis()});}catch{return fail(res,500,'DASHBOARD_ERROR','Unable to load admin dashboard.');}});
router.get('/auditor',requireAuth,allowRoles('auditor','fleet_admin'),async(_req,res)=>{try{const r=await pool.query(`SELECT COUNT(*)::int count FROM audit_events`);return ok(res,{auditEvents:r.rows[0].count,kpis:await operationalKpis()});}catch{return fail(res,500,'DASHBOARD_ERROR','Unable to load auditor dashboard.');}});
module.exports=router;
