const express=require('express');const {pool}=require('../config/db');const {ok,fail,pagination,paged,audit,notify,addTripHistory,userId}=require('../utils');const {requireAuth,allowRoles,normalizeRole}=require('../middleware/auth');const router=express.Router();

async function isAssignedDriver(clientOrPool, userSub, assignedDriverId) {
  if (!userSub || assignedDriverId == null) return false;
  const subStr = String(userSub);
  const assignedStr = String(assignedDriverId);
  if (subStr === assignedStr) return true;
  const res = await clientOrPool.query(
    `SELECT 1 FROM drivers WHERE CAST(user_id AS TEXT) = $1 AND CAST(driver_id AS TEXT) = $2 LIMIT 1`,
    [subStr, assignedStr]
  );
  return res.rows.length > 0;
}

router.get('/my',requireAuth,async(req,res)=>{try{const sub=String(userId(req));const r=await pool.query(`SELECT t.*,r.vehicle_id,r.origin,r.destination,r.trip_start_timestamp,r.trip_end_timestamp,r.status AS reservation_status FROM trips t JOIN reservations r ON r.reservation_id=t.reservation_id LEFT JOIN drivers d ON (d.driver_id=t.driver_id OR d.driver_id=r.driver_id) WHERE CAST(t.driver_id AS TEXT)=$1 OR CAST(r.driver_id AS TEXT)=$1 OR CAST(d.user_id AS TEXT)=$1 OR CAST(r.requester_id AS TEXT)=$1 ORDER BY t.created_at DESC`,[sub]);return ok(res,r.rows);}catch(e){return fail(res,500,'TRIPS_ERROR','Unable to list your trips.');}});
router.get('/:id',requireAuth,async(req,res)=>{try{const r=await pool.query(`SELECT t.*,r.vehicle_id,r.driver_id AS reservation_driver_id,r.status AS reservation_status,r.origin,r.destination FROM trips t JOIN reservations r ON r.reservation_id=t.reservation_id WHERE t.trip_id=$1`,[req.params.id]);if(!r.rows[0])return fail(res,404,'TRIP_NOT_FOUND','Trip not found.');return ok(res,r.rows[0]);}catch(e){return fail(res,500,'TRIP_ERROR','Unable to get trip.');}});
router.post('/:id/assign',requireAuth,allowRoles('dispatcher','fleet_admin'),async(req,res)=>{const {vehicleId,driverId,reason}=req.body;const client=await pool.connect();try{await client.query('BEGIN');const r=await client.query(`SELECT t.*,r.* FROM trips t JOIN reservations r ON r.reservation_id=t.reservation_id WHERE t.trip_id=$1 FOR UPDATE`,[req.params.id]);if(!r.rows[0]){await client.query('ROLLBACK');return fail(res,404,'TRIP_NOT_FOUND','Trip not found.');}const x=r.rows[0];await client.query(`SELECT pg_advisory_xact_lock(hashtext($1))`,[String(vehicleId)]);const conflict=await client.query(`SELECT reservation_id FROM reservations WHERE vehicle_id=$1 AND reservation_id<>$2 AND status IN('approved','active') AND trip_start_timestamp<$4 AND trip_end_timestamp>$3 LIMIT 1`,[vehicleId,x.reservation_id,x.trip_start_timestamp,x.trip_end_timestamp]);if(conflict.rows[0]){await client.query('ROLLBACK');return fail(res,409,'VEHICLE_CONFLICT','Vehicle overlaps another trip.');}await client.query(`UPDATE reservations SET vehicle_id=$1,driver_id=$2 WHERE reservation_id=$3`,[vehicleId,driverId,x.reservation_id]);await client.query(`UPDATE trips SET driver_id=$1 WHERE trip_id=$2`,[driverId,req.params.id]);await client.query('COMMIT');await audit(userId(req),'ASSIGN_DRIVER','trip',req.params.id,{driverId,vehicleId,reason});await audit(userId(req),'ASSIGN_VEHICLE','trip',req.params.id,{vehicleId,driverId});return ok(res,{tripId:req.params.id,vehicleId,driverId},'Trip assigned');}catch(e){try{await client.query('ROLLBACK')}catch{};return fail(res,500,'ASSIGN_ERROR','Unable to assign trip.');}finally{client.release();}});
router.post('/:id/dispatch',requireAuth,allowRoles('dispatcher','fleet_admin'),async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const r=await client.query(`SELECT t.*,r.status,r.driver_id,r.vehicle_id FROM trips t JOIN reservations r ON r.reservation_id=t.reservation_id WHERE t.trip_id=$1 FOR UPDATE`,[req.params.id]);if(!r.rows[0]){await client.query('ROLLBACK');return fail(res,404,'TRIP_NOT_FOUND','Trip not found.');}if(r.rows[0].status!=='approved'){await client.query('ROLLBACK');return fail(res,409,'INVALID_STATUS','Trip must be approved before dispatch.');}await client.query(`UPDATE reservations SET status='dispatched' WHERE reservation_id=$1`,[r.rows[0].reservation_id]);await client.query('COMMIT');await addTripHistory(req.params.id,'approved','dispatched',userId(req),req.body.reason);await audit(userId(req),'DISPATCH_TRIP','trip',req.params.id);return ok(res,null,'Trip dispatched');}catch(e){try{await client.query('ROLLBACK')}catch{};return fail(res,500,'DISPATCH_ERROR','Unable to dispatch trip.');}finally{client.release();}});
router.post('/:id/start',requireAuth,allowRoles('driver'),async(req,res)=>{const {odometerStart,odometer_start,latitude,longitude,timestamp}=req.body;const odo=odometerStart??odometer_start;if(odo==null)return fail(res,400,'VALIDATION_ERROR','odometerStart is required.');const client=await pool.connect();try{await client.query('BEGIN');const r=await client.query(`SELECT t.*,r.driver_id AS res_driver_id,r.status,r.reservation_id FROM trips t JOIN reservations r ON r.reservation_id=t.reservation_id WHERE t.trip_id=$1 FOR UPDATE`,[req.params.id]);if(!r.rows[0]){await client.query('ROLLBACK');return fail(res,404,'TRIP_NOT_FOUND','Trip not found.');}const x=r.rows[0];const assignedDriver=x.driver_id??x.res_driver_id;const authorized=await isAssignedDriver(client,userId(req),assignedDriver);if(!authorized){await client.query('ROLLBACK');return fail(res,403,'FORBIDDEN','Only the assigned driver can start this trip.');}if(!['approved','dispatched'].includes(x.status)){await client.query('ROLLBACK');return fail(res,409,'INVALID_STATUS','Trip is not ready to start.');}await client.query(`UPDATE trips SET start_odometer=$1 WHERE trip_id=$2`,[odo,req.params.id]);await client.query(`UPDATE reservations SET status='active' WHERE reservation_id=$1`,[x.reservation_id]);if(latitude!=null&&longitude!=null)await client.query(`INSERT INTO location_pings(trip_id,latitude,longitude,recorded_at) VALUES($1,$2,$3,COALESCE($4,NOW()))`,[req.params.id,latitude,longitude,timestamp||null]);await client.query('COMMIT');await addTripHistory(req.params.id,x.status,'active',userId(req));await audit(userId(req),'START_TRIP','trip',req.params.id);return ok(res,{tripId:Number(req.params.id),status:'active'},'Trip started');}catch(e){try{await client.query('ROLLBACK')}catch{};return fail(res,500,'START_ERROR','Unable to start trip.');}finally{client.release();}});
router.post('/:id/locations',requireAuth,allowRoles('driver'),async(req,res)=>{const {latitude,longitude,timestamp,accuracyMeters,speedKmh}=req.body;if(latitude==null||longitude==null||!timestamp)return fail(res,400,'VALIDATION_ERROR','latitude, longitude and timestamp are required.');try{const r=await pool.query(`SELECT t.*,r.driver_id AS res_driver_id,r.status FROM trips t JOIN reservations r ON r.reservation_id=t.reservation_id WHERE t.trip_id=$1`,[req.params.id]);if(!r.rows[0])return fail(res,404,'TRIP_NOT_FOUND','Trip not found.');if(r.rows[0].status!=='active')return fail(res,409,'INVALID_STATUS','Locations are accepted only for active trips.');const assignedDriver=r.rows[0].driver_id??r.rows[0].res_driver_id;const authorized=await isAssignedDriver(pool,userId(req),assignedDriver);if(!authorized)return fail(res,403,'FORBIDDEN','Only the assigned driver can send location.');const t=new Date(timestamp);if(Number.isNaN(t.getTime())||t.getTime()>Date.now()+5*60*1000)return fail(res,400,'INVALID_TIMESTAMP','Location timestamp is invalid or in the future.');if(Math.abs(Number(latitude))>90||Math.abs(Number(longitude))>180)return fail(res,400,'INVALID_COORDINATES','Coordinates are invalid.');const last=await pool.query(`SELECT latitude,longitude,recorded_at FROM location_pings WHERE trip_id=$1 ORDER BY recorded_at DESC LIMIT 1`,[req.params.id]);if(last.rows[0]){const dt=Math.max(.001,(t-new Date(last.rows[0].recorded_at))/3600000);const km=Math.sqrt((Number(latitude)-Number(last.rows[0].latitude))**2+(Number(longitude)-Number(last.rows[0].longitude))**2)*111;if(km/dt>180)return fail(res,400,'IMPOSSIBLE_LOCATION_JUMP','Location jump is not plausible.');}const p=await pool.query(`INSERT INTO location_pings(trip_id,latitude,longitude,recorded_at,accuracy_meters,speed_kmh) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[req.params.id,latitude,longitude,t,accuracyMeters||null,speedKmh||null]);return ok(res,p.rows[0],'Location recorded',201);}catch(e){return fail(res,500,'LOCATION_ERROR','Unable to record location.');}});
router.get('/:id/location/latest',requireAuth,async(req,res)=>{const r=await pool.query(`SELECT * FROM location_pings WHERE trip_id=$1 ORDER BY recorded_at DESC LIMIT 1`,[req.params.id]);return ok(res,r.rows[0]||null);});
router.get('/:id/locations',requireAuth,async(req,res)=>{const vals=[req.params.id];let where='trip_id=$1';if(req.query.from){vals.push(req.query.from);where+=` AND recorded_at>=$${vals.length}`;}if(req.query.to){vals.push(req.query.to);where+=` AND recorded_at<=$${vals.length}`;}const r=await pool.query(`SELECT * FROM location_pings WHERE ${where} ORDER BY recorded_at`,vals);return ok(res,r.rows);});
router.post('/:id/complete',requireAuth,allowRoles('driver'),async(req,res)=>{const b=req.body;const end=b.odometerEnd??b.end_odometer,dist=b.actualDistanceKm??b.actual_distance_km,fuel=b.actualFuelLiters??b.actual_fuel_used_liters;if(end==null||dist==null||fuel==null)return fail(res,400,'VALIDATION_ERROR','odometerEnd, actualDistanceKm and actualFuelLiters are required.');const client=await pool.connect();try{await client.query('BEGIN');const r=await client.query(`SELECT t.*,r.driver_id AS res_driver_id,r.status,r.reservation_id,r.vehicle_id,r.requester_id FROM trips t JOIN reservations r ON r.reservation_id=t.reservation_id WHERE t.trip_id=$1 FOR UPDATE`,[req.params.id]);if(!r.rows[0]){await client.query('ROLLBACK');return fail(res,404,'TRIP_NOT_FOUND','Trip not found.');}if(r.rows[0].status!=='active'){await client.query('ROLLBACK');return fail(res,409,'INVALID_STATUS','Only active trips can be completed.');}const assignedDriver=r.rows[0].driver_id??r.rows[0].res_driver_id;const authorized=await isAssignedDriver(client,userId(req),assignedDriver);if(!authorized){await client.query('ROLLBACK');return fail(res,403,'FORBIDDEN','Only the assigned driver can complete this trip.');}if(Number(end)<Number(r.rows[0].start_odometer)){await client.query('ROLLBACK');return fail(res,400,'INVALID_ODOMETER','End odometer cannot be lower than start odometer.');}await client.query(`UPDATE trips SET end_odometer=$1,actual_distance_km=$2,actual_fuel_used_liters=$3 WHERE trip_id=$4`,[end,dist,fuel,req.params.id]);await client.query(`UPDATE reservations SET status='completed',actual_fuel_liters=$1,trip_end_timestamp=NOW() WHERE reservation_id=$2`,[fuel,r.rows[0].reservation_id]);if(r.rows[0].vehicle_id){await client.query(`UPDATE vehicles SET current_odometer=GREATEST(COALESCE(current_odometer,0),$1) WHERE vehicle_id=$2`,[end,r.rows[0].vehicle_id]);}await client.query('COMMIT');await addTripHistory(req.params.id,'active','completed',userId(req),b.notes);await audit(userId(req),'COMPLETE_TRIP','trip',req.params.id,{actualDistanceKm:dist,actualFuelLiters:fuel});await notify(r.rows[0].requester_id,'Trip completed','Your trip has been completed.');return ok(res,{tripId:Number(req.params.id),status:'completed'},'Trip completed');}catch(e){try{await client.query('ROLLBACK')}catch{};return fail(res,500,'COMPLETE_ERROR','Unable to complete trip.');}finally{client.release();}});
router.get('/:id/fuel',requireAuth,async(req,res)=>{const r=await pool.query(`SELECT * FROM fuel_transactions WHERE trip_id=$1 ORDER BY recorded_at`,[req.params.id]);return ok(res,r.rows);});
router.post('/:id/fuel',requireAuth,allowRoles('driver','dispatcher','fleet_admin'),async(req,res)=>{const b=req.body;if(b.liters==null||b.cost==null)return fail(res,400,'VALIDATION_ERROR','liters and cost are required.');try{const userRole=normalizeRole(req.user?.role);if(userRole==='driver'){const r=await pool.query(`SELECT t.driver_id,r.driver_id AS res_driver_id FROM trips t JOIN reservations r ON r.reservation_id=t.reservation_id WHERE t.trip_id=$1`,[req.params.id]);if(!r.rows[0])return fail(res,404,'TRIP_NOT_FOUND','Trip not found.');const assignedDriver=r.rows[0].driver_id??r.rows[0].res_driver_id;const authorized=await isAssignedDriver(pool,userId(req),assignedDriver);if(!authorized)return fail(res,403,'FORBIDDEN','Only the assigned driver can log fuel for this trip.');}const r=await pool.query(`INSERT INTO fuel_transactions(trip_id,liters,cost,odometer,recorded_at) VALUES($1,$2,$3,$4,COALESCE($5,NOW())) RETURNING *`,[req.params.id,b.liters,b.cost,b.odometer||null,b.timestamp||null]);return ok(res,r.rows[0],'Fuel transaction added',201);}catch(e){return fail(res,400,'FUEL_TRANSACTION_ERROR','Unable to add fuel transaction.');}});
router.get('/:id/status-history',requireAuth,async(req,res)=>{const r=await pool.query(`SELECT * FROM trip_status_history WHERE trip_id=$1 ORDER BY changed_at`,[req.params.id]);return ok(res,r.rows);});
module.exports=router;
