const express=require('express'); const {pool}=require('../config/db');
const {ok,fail,pagination,paged,audit,userId}=require('../utils'); const {requireAuth,allowRoles}=require('../middleware/auth');
const router=express.Router();
router.get('/',requireAuth,async(req,res)=>{
 const {type,model,minSeats,maxSeats,transmission,fuelType,accessibility,status,availableFrom,availableTo,search,brandId}=req.query; const {page,limit,offset}=pagination(req);
 const vals=[],w=[];
 const add=(sql,v)=>{vals.push(v);w.push(sql.replace('?',`$${vals.length}`));};
 if(type)add(`vehicle_type ILIKE ?`,type); if(model)add(`model ILIKE ?`,model); if(minSeats)add(`seats>=?`,Number(minSeats)); if(maxSeats)add(`seats<=?`,Number(maxSeats)); if(transmission)add(`transmission ILIKE ?`,transmission); if(fuelType)add(`fuel_type ILIKE ?`,fuelType); if(status)add(`service_status ILIKE ?`,status); if(search){vals.push(`%${search}%`);w.push(`(vehicle_id ILIKE $${vals.length} OR make ILIKE $${vals.length} OR model ILIKE $${vals.length} OR plate_number ILIKE $${vals.length})`);}
 if(accessibility==='true')w.push(`COALESCE(accessibility_features,'')<>''`);
 try{const where=w.length?`WHERE ${w.join(' AND ')}`:'';const c=await pool.query(`SELECT COUNT(*)::int total FROM vehicles ${where}`,vals);const r=await pool.query(`SELECT * FROM vehicles ${where} ORDER BY vehicle_id LIMIT ${limit} OFFSET ${offset}`,vals);
  return paged(res,r.rows,c.rows[0].total,page,limit);
 }catch(e){console.error(e);return fail(res,500,'VEHICLES_ERROR','Unable to list vehicles.');}
});
router.get('/:id',requireAuth,async(req,res)=>{try{const r=await pool.query(`SELECT * FROM vehicles WHERE vehicle_id=$1`,[req.params.id]);if(!r.rows[0])return fail(res,404,'VEHICLE_NOT_FOUND','Vehicle not found.');const s=await pool.query(`SELECT * FROM vehicle_specifications WHERE vehicle_id=$1`,[req.params.id]);const p=await pool.query(`SELECT * FROM vehicle_photos WHERE vehicle_id=$1`,[req.params.id]);return ok(res,{...r.rows[0],specification:s.rows[0]||null,photos:p.rows});}catch(e){return fail(res,500,'VEHICLE_ERROR','Unable to get vehicle.');}});
router.post('/',requireAuth,allowRoles('fleet_admin'),async(req,res)=>{const b=req.body;if(!b.vehicleId)return fail(res,400,'VALIDATION_ERROR','vehicleId is required.');try{const r=await pool.query(`INSERT INTO vehicles(vehicle_id,vehicle_type,make,model,vehicle_year,seats,fuel_type,nominal_l_per_100km,allowed_load_kg,service_status,plate_number,transmission,fuel_tank_capacity_l,accessibility_features,current_odometer) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,[b.vehicleId,b.vehicleType,b.make,b.model,b.vehicleYear,b.seats,b.fuelType,b.nominalLPer100Km,b.allowedLoad,b.status||'available',b.plateNumber,b.transmission,b.tankCapacity,b.accessibilityFeatures,b.currentOdometer]);await audit(req.user.sub,'CREATE_VEHICLE','vehicle',b.vehicleId);return ok(res,r.rows[0],'Vehicle created',201);}catch(e){return fail(res,400,'CREATE_VEHICLE_ERROR',e.message);}});
router.put('/:id',requireAuth,allowRoles('fleet_admin'),async(req,res)=>{const b=req.body;try{const r=await pool.query(`UPDATE vehicles SET vehicle_type=COALESCE($1,vehicle_type),make=COALESCE($2,make),model=COALESCE($3,model),vehicle_year=COALESCE($4,vehicle_year),seats=COALESCE($5,seats),fuel_type=COALESCE($6,fuel_type),nominal_l_per_100km=COALESCE($7,nominal_l_per_100km),allowed_load_kg=COALESCE($8,allowed_load_kg),plate_number=COALESCE($9,plate_number),transmission=COALESCE($10,transmission),fuel_tank_capacity_l=COALESCE($11,fuel_tank_capacity_l),accessibility_features=COALESCE($12,accessibility_features) WHERE vehicle_id=$13 RETURNING *`,[b.vehicleType,b.make,b.model,b.vehicleYear,b.seats,b.fuelType,b.nominalLPer100Km,b.allowedLoad,b.plateNumber,b.transmission,b.tankCapacity,b.accessibilityFeatures,req.params.id]);if(!r.rows[0])return fail(res,404,'VEHICLE_NOT_FOUND','Vehicle not found.');await audit(req.user.sub,'UPDATE_VEHICLE','vehicle',req.params.id);return ok(res,r.rows[0],'Vehicle updated');}catch(e){return fail(res,400,'UPDATE_VEHICLE_ERROR','Unable to update vehicle.');}});
router.patch('/:id/status',requireAuth,allowRoles('fleet_admin','dispatcher'),async(req,res)=>{const {status}=req.body;if(!['available','unavailable','maintenance','inactive'].includes(status))return fail(res,400,'INVALID_STATUS','Invalid vehicle status.');try{const r=await pool.query(`UPDATE vehicles SET service_status=$1 WHERE vehicle_id=$2 RETURNING *`,[status,req.params.id]);if(!r.rows[0])return fail(res,404,'VEHICLE_NOT_FOUND','Vehicle not found.');await audit(req.user.sub,'CHANGE_VEHICLE_STATUS','vehicle',req.params.id,{status});return ok(res,r.rows[0],'Vehicle status updated');}catch(e){return fail(res,400,'STATUS_ERROR','Unable to update vehicle status.');}});
router.delete('/:id',requireAuth,allowRoles('fleet_admin'),async(req,res)=>{try{const r=await pool.query(`UPDATE vehicles SET service_status='inactive' WHERE vehicle_id=$1 RETURNING vehicle_id,service_status`,[req.params.id]);if(!r.rows[0])return fail(res,404,'VEHICLE_NOT_FOUND','Vehicle not found.');await audit(req.user.sub,'ARCHIVE_VEHICLE','vehicle',req.params.id);return ok(res,r.rows[0],'Vehicle archived');}catch(e){return fail(res,400,'ARCHIVE_ERROR','Unable to archive vehicle.');}});
router.get('/:id/availability',requireAuth,async(req,res)=>{try{const r=await pool.query(`SELECT trip_start_timestamp AS start,trip_end_timestamp AS "end",status FROM reservations WHERE vehicle_id=$1 AND trip_start_timestamp IS NOT NULL AND trip_end_timestamp IS NOT NULL AND ($2::timestamp IS NULL OR trip_end_timestamp>$2) AND ($3::timestamp IS NULL OR trip_start_timestamp<$3) AND status IN('approved','active','pending') ORDER BY trip_start_timestamp`,[req.params.id,req.query.from||null,req.query.to||null]);const m=await pool.query(`SELECT start_at AS start,end_at AS "end",'maintenance' AS status FROM maintenance_records WHERE vehicle_id=$1 AND status<>'completed' ORDER BY start_at`,[req.params.id]);return ok(res,{vehicleId:req.params.id,availability:[...r.rows,...m.rows]});}catch(e){return fail(res,500,'AVAILABILITY_ERROR','Unable to get availability.');}});
router.post('/check-availability',requireAuth,async(req,res)=>{const {vehicleId,startTime,endTime}=req.body;if(!vehicleId||!startTime||!endTime)return fail(res,400,'VALIDATION_ERROR','vehicleId, startTime and endTime are required.');try{const r=await pool.query(`SELECT reservation_id,trip_start_timestamp AS start,trip_end_timestamp AS "end",status FROM reservations WHERE vehicle_id=$1 AND status IN('approved','active') AND trip_start_timestamp<$3 AND trip_end_timestamp>$2`,[vehicleId,startTime,endTime]);const m=await pool.query(`SELECT maintenance_id,start_at AS start,end_at AS "end" FROM maintenance_records WHERE vehicle_id=$1 AND status<>'completed' AND start_at<$3 AND end_at>$2`,[vehicleId,startTime,endTime]);return ok(res,{available:r.rows.length===0&&m.rows.length===0,conflicts:[...r.rows,...m.rows]});}catch(e){return fail(res,500,'AVAILABILITY_ERROR','Unable to check availability.');}});
router.get('/:id/odometer',requireAuth,async(req,res)=>{try{const r=await pool.query(`SELECT * FROM odometer_readings WHERE vehicle_id=$1 ORDER BY recorded_at DESC`,[req.params.id]);return ok(res,r.rows);}catch(e){return fail(res,500,'ODOMETER_ERROR','Unable to get odometer history.');}});
router.post('/:id/odometer',requireAuth,async(req,res)=>{const {value,recordedAt}=req.body;if(value==null)return fail(res,400,'VALIDATION_ERROR','value is required.');try{const r=await pool.query(`INSERT INTO odometer_readings(vehicle_id,value,recorded_at,recorded_by) VALUES($1,$2,COALESCE($3,NOW()),$4) RETURNING *`,[req.params.id,value,recordedAt||null,userId(req)]);await pool.query(`UPDATE vehicles SET current_odometer=$1 WHERE vehicle_id=$2`,[value,req.params.id]);await audit(userId(req),'RECORD_ODOMETER','vehicle',req.params.id,{value});return ok(res,r.rows[0],'Odometer recorded',201);}catch(e){return fail(res,400,'ODOMETER_ERROR','Unable to record odometer.');}});
module.exports=router;
